.github/workflows/doc_gen.yaml

Add CI action to automatically deploy API to pages

[ci] Add action for Doxygen publish

---

.github/workflows/doc_gen.yaml
.github/workflows/main.yaml
README.md

Using Doxygen to generate HTML and publish to GH pages

[ci] Add action to generate and deploy ODLA API

---

ODLA/include/ODLA/ops/odla_ops_math.h

Add GE, LE and NE ops for odla math ops

[ODLA] Add logical ops

---

ODLA/platforms/odla_tensorrt.cc

Implement odla_And, odla_Equal, odla_NotEqual etc. logical op for
odla_tensorrt.

[ODLA] Implement logical ops for odla_trt

---

lib/parser/tensorflow/tf_parser.cc
lib/transforms/onnxextension_legalizer.cc

- [Bug] Fix TFParser attribute
- [Bug] Fix Unsqueeze

[Bug] Fix TF parser and unsqueeze

---

include/halo/lib/ir/tf_convert.td
lib/transforms/type_legalizer.cc

1. Add TanH mapping for TF
2. fix TopK type inference

Fix topk & add Tanh for TF 

---

ODLA/platforms/CMakeLists.txt
ODLA/platforms/odla_dnnl.cc
utils/docker/Dockerfile

Implementation from Intel support.

[ODLA DNNL] Implement ops for avx512 & bf16

---

include/halo/lib/ir/tf_convert.td
lib/transforms/type_legalizer.cc

[TF] Support BatchMatMulV2

---

ODLA/platforms/dnnl/dnnl_utils.h
ODLA/platforms/dnnl/dnnl_utils_avx512.h
ODLA/platforms/dnnl/odla_dnnl.cc
lib/transforms/type_legalizer.cc

1. Add NMS op
2. Add S32 eltwise op
3. Bug fix for lambda capture

[ODLA DNNL] Multiple ops support from Intel

---

include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/add.cc
lib/target/generic_cpp/cast.cc
lib/target/generic_cpp/reduce_mean.cc

Emit odla_Neg, odla_Not, odla_reduce_xxx, odla_cast etc.

[CG] Emit more odla ops

---

include/halo/lib/ir/caffe_convert.td
lib/transforms/caffeextension_legalizer.cc

[Caffe] Support Tile

---

ODLA/platforms/odla_popart/odla_compute.cc

[ODLA] fix odla popart build error

---

lib/parser/caffe/caffe_parser.cc

This is similar to the logic in Caffe's CopyTrainedLayersFrom() function.

[CaffeParser] Match weights params with net layer by names

---

include/halo/lib/ir/tflite_convert.td
include/halo/lib/transforms/transforms_util.h
lib/parser/tflite/tflite_parser.cc
lib/transforms/onnxextension_legalizer.cc
lib/transforms/tfliteextension_legalizer.cc
lib/transforms/transforms_util.cc

add tflite squeeze op, fix tflite parser mobilenet_v1 error issue

[TFLite Parser] Support tflite squeeze op

---

include/halo/lib/ir/caffe_convert.td

Signed-off-by: Peng Liang <pengliang.peng@alibaba-inc.com>

Caffe: add sigmoid op mapping

---

include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/relu.cc

[CodeGen] Generate Elu op

---

ODLA/platforms/odla_popart/odla_compute.cc

fix segment fault due to input/output bind error

[ODLA] Fix segment fault

---

ODLA/platforms/odla_popart/common.cc
ODLA/platforms/odla_popart/common.h
ODLA/platforms/odla_popart/custom_ops/erf.cc
ODLA/platforms/odla_popart/custom_ops/erf_test.cc
ODLA/platforms/odla_popart/custom_ops/erf_test.py
ODLA/platforms/odla_popart/custom_ops/rsqrt.cc
ODLA/platforms/odla_popart/custom_ops/rsqrt_test.cc
ODLA/platforms/odla_popart/custom_ops/rsqrt_test.py
ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_device.cc
ODLA/platforms/odla_popart/odla_ops.cc
ODLA/platforms/odla_popart/odla_ops_math.cc
ODLA/platforms/odla_popart/odla_ops_nn.cc
ODLA/platforms/odla_popart/odla_ops_process.cc
ODLA/platforms/odla_popart/odla_popart.h

add missing Apache License 2.0

[ODLA] add license

---

README.md
docs/how_to_build.md

1.  Add IPU build/test status badge
2. Add docker image location

[Doc] Readme update

---

utils/docker/start_docker_cpu.sh

Use the docker image from aliyun

[Docker] Update docker starting script

---

ODLA/platforms/dnnl/dnnl_utils_avx512.h
ODLA/platforms/dnnl/odla_dnnl.cc
lib/target/generic_cpp/generic_cxx_codegen.cc
tests/unittests/lit_cases/test_dnnl/test_globalaveragepool_precomputed_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_lrn_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_mean_default_axes_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_mean_default_axes_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_popart/test_globalaveragepool_precomputed_popart.cc
tests/unittests/lit_cases/test_popart/test_min_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_mean_default_axes_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_mean_default_axes_keepdims_random_popart.cc
tests/unittests/lit_cases/test_tensorrt/test_globalaveragepool_precomputed_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_mean_default_axes_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_mean_default_axes_keepdims_random_tensorrt.cc
tests/unittests/unittests.h
tests/unittests/unittests.tpp

Also fix DNNL for arguments of int64 (for indices) and gather op for
axes > 0.

[Unit Test] Fix bug in result compare

---

lib/pass/pass_manager.cc

The original pass manager did not return the correct 'changed' status.

[BugFix] Status returned by PassManager

---

.github/actions/build/action.yaml
.github/actions/build/build_in_docker.sh
.github/workflows/ipu_sim.yaml
.github/workflows/main.yaml
include/halo/lib/parser/parser.h
lib/parser/caffe/caffe_parser.cc
lib/parser/onnx/onnx_parser.cc
lib/parser/parser.cc
lib/parser/tensorflow/CMakeLists.txt
lib/parser/tensorflow/tf_parser.cc
lib/parser/tflite/tflite_parser.cc

The original pass manager did not return the correct 'changed' status.

Actions Update

---

ODLA/platforms/tensorrt/CMakeLists.txt
include/halo/lib/ir/tflite_convert.td

[TFLite] Fix parsing of pooling and fc

---

README.md

[Doc] Fix typo in Readme.md

---

lib/transforms/inst_simplify.cc

Fuse deconv bn

---

include/halo/lib/ir/caffe_convert.td
include/halo/lib/ir/onnx_convert.td
lib/transforms/caffeextension_legalizer.cc

Handle ceil_mode of pooling

---

include/halo/lib/ir/extension_instructions.h
include/halo/lib/ir/onnx_convert.td
include/halo/lib/ir/tf_convert.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/parser/onnx/onnx_parser.cc
lib/target/generic_cpp/CMakeLists.txt
lib/target/generic_cpp/hgengine.cc
lib/transforms/onnxextension_legalizer.cc
lib/transforms/tfextension_legalizer.cc
lib/transforms/type_legalizer.cc

Add NPU HALO support

---

lib/transforms/input_legalizer.cc

Enable specifying simple preprocessing logic (add/div) 

---

ODLA/platforms/tensorrt/odla_tensorrt.cc
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/CMakeLists.txt
lib/target/generic_cpp/random.cc

Add support for random uniform op

---

.github/actions/build/build_in_docker.sh

[CI] Set DNNL_COMPILER to gcc-10

---

.gitignore
include/halo/lib/transforms/transforms_util.h
lib/parser/onnx/onnx_parser.cc
lib/transforms/caffeextension_legalizer.cc
lib/transforms/onnxextension_legalizer.cc
lib/transforms/tfextension_legalizer.cc
lib/transforms/transforms_util.cc

Extend util funcs

---

lib/target/generic_cpp/generic_cxx_codegen.cc
lib/transforms/dce.cc
models/vision/detection/yolo/run_yolo.sh

[Tests][YOLO] cleanup temp files before running

---

lib/target/codegen.cc

[CXXCodeGen] Escape colon in name

---

include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/parser/caffe/CMakeLists.txt
lib/target/generic_cpp/CMakeLists.txt
lib/target/generic_cpp/reduction.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_default_axes_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_default_axes_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_do_not_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_do_not_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_default_axes_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_default_axes_keepdims_random_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_do_not_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_do_not_keepdims_random_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_keepdims_random_popart.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_default_axes_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_default_axes_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_do_not_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_do_not_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_keepdims_random_tensorrt.cc

[CodeGen] Support reduce_min & reduce_max

---

lib/transforms/inst_simplify.cc

[Opt] Remove redundant add/sub

---

include/halo/lib/transforms/inst_simplify.h
lib/transforms/inst_simplify.cc

[Opt] Remove Ceil with constant input

---

include/halo/lib/ir/basic_block.h
lib/parser/onnx/onnx_parser.cc
lib/parser/onnx/onnx_parser.h

[ONNX Parser] Support subgraph with same node id

---

lib/framework/type.cc
lib/target/generic_llvmir/generic_constant_writer.cc
lib/target/generic_llvmir/generic_llvmir_codegen.cc

[CodeGen] Handle bool type constants

---

ODLA/platforms/tensorrt/odla_tensorrt.cc
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/pass/pass_manager.cc
lib/target/generic_cpp/add.cc
lib/transforms/inst_simplify.cc
lib/transforms/onnxextension_legalizer.cc
tests/unittests/lit_cases/test_dnnl/test_split_equal_parts_1d_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_split_equal_parts_2d_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_split_equal_parts_default_axis_dnnl.cc
tests/unittests/lit_cases/test_popart/test_pow_bcast_array_popart.cc
tests/unittests/lit_cases/test_popart/test_pow_bcast_scalar_popart.cc
tests/unittests/lit_cases/test_popart/test_pow_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reciprocal_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reciprocal_popart.cc
tests/unittests/lit_cases/test_popart/test_split_equal_parts_1d_popart.cc
tests/unittests/lit_cases/test_popart/test_split_equal_parts_2d_popart.cc
tests/unittests/lit_cases/test_popart/test_split_equal_parts_default_axis_popart.cc
tests/unittests/lit_cases/test_popart/test_tanh_example_popart.cc
tests/unittests/lit_cases/test_popart/test_tanh_popart.cc
tests/unittests/lit_cases/test_tensorrt/test_pow_bcast_array_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_pow_bcast_scalar_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_pow_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reciprocal_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reciprocal_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_split_equal_parts_1d_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_split_equal_parts_2d_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_split_equal_parts_default_axis_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_tanh_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_tanh_tensorrt.cc
utils/tablegen/inst_info_emitter.cc

Parser/CG/ODLA trt changes for onnx bert-squad.

Support onnx bert-squad

---

cmake/modules/protobuf.cmake

[libhalo] Allow link with static protobuf library

---

armory/analyzer/driver.cc
armory/diagnostic/driver.cc
driver/driver.cc
include/halo/halo.h
include/halo/lib/framework/common.h
include/halo/lib/parser/parser.h
include/halo/lib/pass/pass_manager.h
include/halo/lib/quantizer/weights_quantizer.h
include/halo/lib/target/codegen.h
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
include/halo/lib/target/generic_llvmir/generic_llvmir_codegen.h
include/halo/lib/transforms/fusion.h
include/halo/lib/transforms/reorder_channel.h
include/halo/utils/cl_options.h
include/halo/utils/passes_helper.h
lib/CMakeLists.txt
lib/interface/CMakeLists.txt
lib/interface/interface.cc
lib/parser/parser.cc
lib/pass/pass_manager.cc
lib/quantizer/weights_quantizer.cc
lib/target/generic_cpp/generic_cxx_codegen.cc
lib/target/generic_cpp/return.cc
tests/lit.cfg.py
utils/tablegen/fusion_emitter.cc

Expose the compilation functionality to libhalo users.

[HALO Lib] Add interface to libhalo

---

ODLA/platforms/odla_popart/common.cc

Fix compilation warnings

---

lib/parser/tflite/tflite_parser.cc

[Bug] Fix TFlite Parser

---

lib/target/generic_cpp/generic_cxx_codegen.cc

[Bug][CXX CodeGen] Normalize function name

---

armory/analyzer/driver.cc
armory/diagnostic/driver.cc
driver/driver.cc
include/halo/utils/cl_options.h
utils/tablegen/fusion_emitter.cc

[Bug] Hide unrelated options listed in '--help' 

---

cmake/modules/zbuild_llvm.cmake
driver/driver.cc
include/halo/halo.h
include/halo/lib/pass/pass_manager.h
include/halo/lib/target/generic_cxx/code_formatter.h
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
include/halo/utils/passes_helper.h
lib/interface/interface.cc
lib/pass/pass_manager.cc
lib/target/cpu/arm/CMakeLists.txt
lib/target/cpu/riscv/CMakeLists.txt
lib/target/cpu/x86/CMakeLists.txt
lib/target/generic_cpp/CMakeLists.txt
lib/target/generic_cpp/code_formatter.cc
lib/target/generic_cpp/generic_cxx_codegen.cc
lib/target/generic_cpp/generic_cxx_constant_writer.cc
lib/target/generic_llvmir/CMakeLists.txt
tests/compile/test_cxx_gen.in
tests/ir/test_tf_batch_to_space.cc
tests/ir/test_tf_space_to_batch.cc
tests/transforms/test_fuse_scale_conv2d.cc

This removes the need of external program of clang-format

Add CodeFormat pass to format generated ODLA code

---

external/protos/tensorflow/function.proto
lib/parser/tensorflow/tf_parser.cc
lib/parser/tensorflow/tf_parser.h

Support TF Arg node

---

ODLA/platforms/dnnl/odla_dnnl.cc
ODLA/platforms/odla_popart/common.cc
ODLA/platforms/odla_popart/common.h
ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_popart.h
ODLA/platforms/tensorrt/odla_tensorrt.cc
driver/driver.cc
include/halo/halo.h
lib/target/generic_cpp/generic_cxx_codegen.cc
lib/target/generic_llvmir/generic_llvmir_codegen.cc
lib/target/jit_compiler/cxx_jit_compiler.cc
lib/target/jit_compiler/generic_jit_linker.cc

Implement more ops like GetNumOfArguments, GetArgumentById,  GetNumOfOutputs, GetValueType, etc.

[ODLA] Implement more ops

---

include/halo/lib/ir/tf_convert.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/reduction.cc

[CodeGen] Support reduce sum op

---

include/halo/lib/ir/tf_convert.td
include/halo/lib/target/codegen.h
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/codegen.cc
lib/target/generic_cpp/CMakeLists.txt
lib/target/generic_cpp/custom.cc
lib/transforms/tfextension_legalizer.cc

Support generic custom op and handle special TF custom of "Ipu_Gelu"

Support custom op

---

lib/parser/tensorflow/tf_parser.cc
lib/parser/tensorflow/tf_parser.h

Explicitly merge all RetVal node as ReturnInst

[TFParser] Handle RetVal

---

include/halo/lib/ir/common_instructions.td
include/halo/lib/ir/tf_convert.td
include/halo/lib/transforms/inst_simplify.h
lib/transforms/inst_simplify.cc
lib/transforms/tfextension_legalizer.cc
lib/transforms/type_legalizer.cc

Convert TF style slice to Halo slice 
and support more options of strides_slice

[TF] Handle slice & strided_slice

---

include/halo/lib/ir/common_cast_instructions.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/cast.cc
lib/transforms/inst_simplify.cc
lib/transforms/tfextension_legalizer.cc

For casting between FP32 and other FP format

Add Casting Support between different floating point numbers

---

lib/target/generic_cpp/onehot.cc
lib/transforms/inst_simplify.cc
lib/transforms/tfextension_legalizer.cc
lib/transforms/type_legalizer.cc

In IR, on value and off value are two tensors. In ODLA, it's merged.
Also, for TF, the on/off value can be null

Fix OneHot

---

ODLA/platforms/odla_popart/odla_ops_process.cc

The repeat tensor should be INT64 type.

[ODLA/Popart] Fix Tile Op

---

ODLA/platforms/odla_popart/odla_ops.cc

Currently, odla_GEMM calls BatchedMatMaul for tensors with rank of 2.
It ignores the transpose_a/transpos_b/alpha/beta/bias, which is
incorrect.
This patch handles the case by using popart::Gemm.

[ODLA/Popart] Fix GEMM with transpose

---

lib/transforms/typecast.cc

[TypeCast Pass] Allow update argument

---

lib/target/generic_cpp/custom.cc

Fixes the operands emitting of custom op.
This patch fixes #407

[Bug] Fix custom op generation

---

include/halo/lib/transforms/analyzer.h
lib/transforms/analyzer.cc

consider op fusion in mem analysis.
implemented missing ops to support SSD model.

Analyzer updates

---

.github/workflows/main.yaml
.github/workflows/publish_image.yaml

Remove "/" in tag name because it's invalid for docker image tag names

[CI] Fix tags extracting for image publish

---

.github/workflows/main.yaml

This reverts commit 4a20f0d09f6ca181aa730646891e0e25bbd327f4.

Revert "[CI] factor out checkout job"

---

lib/transforms/type_legalizer.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_mean_negative_axes_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_mean_negative_axes_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_negative_axes_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_min_negative_axes_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_popart/test_reduce_mean_negative_axes_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_mean_negative_axes_keepdims_random_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_negative_axes_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_min_negative_axes_keepdims_random_popart.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_l1_negative_axes_keep_dims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_l1_negative_axes_keep_dims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_l2_negative_axes_keep_dims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_l2_negative_axes_keep_dims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_log_sum_exp_negative_axes_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_log_sum_exp_negative_axes_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_log_sum_negative_axes_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_mean_negative_axes_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_mean_negative_axes_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_negative_axes_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_min_negative_axes_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_sum_square_negative_axes_keepdims_example_tensorrt.cc

When the axis op is constant, it should update the axis attribute.

[Bug] Fix axis attribute for reduction instrs

---

include/halo/lib/ir/onnx_convert.td
tests/unittests/lit_cases/test_dnnl/test_reduce_max_default_axes_keepdim_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_default_axes_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_do_not_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_do_not_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_negative_axes_keepdims_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reduce_max_negative_axes_keepdims_random_dnnl.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_default_axes_keepdim_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_default_axes_keepdims_random_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_do_not_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_do_not_keepdims_random_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_keepdims_random_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_negative_axes_keepdims_example_popart.cc
tests/unittests/lit_cases/test_popart/test_reduce_max_negative_axes_keepdims_random_popart.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_default_axes_keepdim_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_default_axes_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_do_not_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_do_not_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_keepdims_random_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_negative_axes_keepdims_example_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_reduce_max_negative_axes_keepdims_random_tensorrt.cc

[ONNX] Add support for reduce_max

---

ODLA/platforms/dnnl/odla_dnnl.cc

Remove unnecessary reorder op and refactor the code

[ODLA/DNNL] Refactor broadcasting handling

---

include/halo/lib/framework/data_layout.h
include/halo/lib/framework/type.h
include/halo/lib/ir/arg_types.td
lib/framework/type.cc
lib/ir/constant.cc
lib/parser/onnx/onnx_parser.cc
lib/target/generic_cpp/generic_cxx_codegen.cc
lib/target/generic_cpp/generic_cxx_constant_writer.cc
lib/target/generic_llvmir/generic_llvmir_codegen.cc

Both HALO IR and parser need support

[ONNX] Add "double" data type support

---

models/lit.cfg.py
tests/unittests/lit_cases/test_tensorrt/lit.local.cfg

Also increase parallelism of onnx/trt lit test

[Tests] Set environmet pass througth for model tests

---

ODLA/include/ODLA/ops/odla_ops_nn.h
ODLA/platforms/dnnl/odla_dnnl.cc
ODLA/platforms/dnnl/odla_dnnl_statistics.cc
include/halo/lib/ir/nn_activation_instructions.td
include/halo/lib/ir/onnx_convert.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/softmax.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_axis_0_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_axis_1_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_axis_2_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_default_axis_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_negative_axis_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_hardmax_one_hot_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_softmax_axis_0_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_softmax_axis_1_dnnl.cc
tests/unittests/lit_cases/test_tensorrt/test_softmax_axis_0_tensorrt.cc
tests/unittests/lit_cases/test_tensorrt/test_softmax_axis_1_tensorrt.cc

Also fix softmax with non-default axis

Add support for Hardmax

---

ODLA/platforms/tensorrt/odla_tensorrt.cc

In TRT 7.0, the plugin version string and interface is changed.

[ODLA/TRT] Fix InstanceNorm

---

ODLA/platforms/dnnl/odla_dnnl.cc
ODLA/platforms/dnnl/odla_dnnl.h
lib/parser/onnx/onnx_parser.cc
lib/target/generic_cpp/generic_cxx_codegen.cc
tests/unittests/lit_cases/test_dnnl/test_clip_default_int8_inbounds_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_clip_default_int8_max_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_clip_default_int8_min_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_max_int8_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_max_uint8_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_maxpool_2d_uint8_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_min_int8_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_min_uint8_dnnl.cc

Also support emit-data-as-c for int8/uint8 data types

[ONNX] Support int8 & uint8

---

ODLA/include/ODLA/odla_common.h
ODLA/platforms/odla_popart/common.cc
ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_device.cc

odla_popart exception improvement

[ODLA] odla_popart exception improvement

---

.github/actions/build/build_in_docker.sh

Build target of "FileCheck" was misplaced.

[CI] Fix build script

---

driver/driver.cc
include/halo/halo.h
include/halo/lib/pass/pass_manager.h
include/halo/lib/transforms/constant_decombine.h
include/halo/utils/passes_helper.h
lib/pass/pass_manager.cc
lib/transforms/CMakeLists.txt
lib/transforms/constant_decombine.cc

add constant decombine pass for ipu sharding mode

---

ODLA/include/ODLA/ops/odla_ops_math.h
ODLA/platforms/dnnl/odla_dnnl.cc
ODLA/platforms/dnnl/odla_dnnl.h
include/halo/lib/ir/math_binary_instructions.td
include/halo/lib/ir/onnx_convert.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/add.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_left_uint16_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_left_uint32_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_left_uint64_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_left_uint8_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_right_uint16_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_right_uint32_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_right_uint64_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_bitshift_right_uint8_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_max_uint16_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_min_uint16_dnnl.cc
utils/tablegen/converter_emitter.cc

Add support for bit shifts

---

lib/target/generic_cpp/gemm.cc

[Bug] Fix GEMM alpha/bata emitting

---

ODLA/include/ODLA/ops/odla_ops_math.h
ODLA/platforms/dnnl/odla_dnnl.cc
ODLA/platforms/dnnl/odla_dnnl.h
include/halo/lib/ir/math_unary_instructions.td
include/halo/lib/ir/onnx_convert.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/add.cc
lib/transforms/type_legalizer.cc
tests/unittests/lit_cases/test_dnnl/test_acos_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_acos_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_asin_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_asin_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_atan_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_atan_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_ceil_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_ceil_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_cos_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_cos_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_cosh_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_cosh_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_isnan_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_round_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_sin_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_sin_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_sinh_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_sinh_example_dnnl.cc
tests/unittests/lit_cases/test_popart/test_sign_popart.cc

Add support for cos, sin, acos, asin, atan, cosh, sinh, ceil, isnan

[ONNX] Multiple support for unary op

---

lib/transforms/onnxextension_legalizer.cc

ONNX defines Bias as concatenation of Wb and Rb, which seems to be unnecessary.
This patch reduces it from [num_dir, 8 * hidden_size] to
[num_dir, 4 * hidden_size]

[ONNX] LSTM Bias reduction

---

lib/transforms/onnxextension_legalizer.cc

ConstantOfShape should fill a tensor with specified shape

[Bug] Fix ConstantOfShape

---

.github/actions/build/build_in_docker.sh
ODLA/platforms/CMakeLists.txt
ODLA/platforms/dnnl/CMakeLists.txt
ODLA/platforms/dnnl/odla_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_acosh_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_acosh_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_asinh_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_asinh_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_atanh_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_atanh_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_neg_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_neg_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reciprocal_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_reciprocal_example_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_sign_dnnl.cc
utils/docker/Dockerfile
utils/docker/Dockerfile.centos
utils/docker/build_image.sh
utils/docker/build_image_centos7.sh
utils/docker/start_docker_cpu.sh

Support atanh, asinh, acosh, recirpocal, sign, neg operator support.

Onnx unary complex

---

ODLA/platforms/tensorrt/common.h
ODLA/platforms/tensorrt/odla_tensorrt.cc
ODLA/platforms/tensorrt/plugins/batchedNMSPlugin/batchedNMSInference.cpp
ODLA/platforms/tensorrt/plugins/batchedNMSPlugin/batchedNMSPlugin.cpp
ODLA/platforms/tensorrt/plugins/batchedNMSPlugin/batchedNMSPlugin.h

Should also work for existing TRT 7

[ODLA/TRT] Adapt for TRT 8.0

---

ODLA/platforms/tensorrt/odla_tensorrt.cc

The scratchpad for int64->int32 is fixed.
For static staic and batch, we can reuse device memory.

[ODLA/TRT] Fix bug and reuse device memory

---

lib/transforms/inst_simplify.cc

Originally, sub(0, x) was simplified to x, which is incorrect.

Fix bug: Sub(0, x) ==> Neg(x)

---

include/halo/lib/ir/math_binary_instructions.td
include/halo/lib/ir/onnx_convert.td
tests/unittests/lit_cases/test_dnnl/test_greater_equal_bcast_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_greater_equal_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_less_equal_bcast_dnnl.cc
tests/unittests/lit_cases/test_dnnl/test_less_equal_dnnl.cc

Patch for greater_or_equal and less_or_equal

---

ODLA/platforms/tensorrt/odla_tensorrt.cc
include/halo/lib/ir/common_instructions.td
include/halo/lib/ir/tf_convert.td
lib/transforms/inst_simplify.cc
lib/transforms/tfextension_legalizer.cc
lib/transforms/type_legalizer.cc

odla trt support: 
1) add  OpSelect,
2) fix elementWise result type when op is logical ones
3) fix gather when input is a bool type tensor
some minor fix and refactor in halo

odla trt support for shoucai

---

lib/transforms/type_legalizer.cc
tests/unittests/lit_cases/test_dnnl/test_xor_bcast4v4d_dnnl.cc

Fixed xor broadcast bug and potential issue for mod and unary operation.

---

.github/workflows/main.yaml

Lint check should be be mandatory and url check can be optional due to network
issues.

[CI] separate url check in docs and lint check

---

.github/actions/build/build_in_docker.sh
ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_pipeline.cc
ODLA/platforms/odla_popart/odla_pipeline.h
ODLA/platforms/odla_popart/odla_popart.cc
ODLA/platforms/odla_popart/odla_popart.h
ODLA/platforms/odla_popart/popart_config.cc
ODLA/platforms/odla_popart/popart_config.h

add a case in odla_SetComputationItem to support pass cache file to odla-popart. The catch file contains config data and graph cache. Popart will analyze config then load graph.

Combine config cache

---

ODLA/platforms/odla_popart/custom_ops/erf.cc
ODLA/platforms/odla_popart/custom_ops/rsqrt.cc
ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_pipeline.cc
ODLA/platforms/odla_popart/odla_pipeline.h
ODLA/platforms/odla_popart/odla_popart.cc
ODLA/platforms/odla_popart/odla_popart.h
ODLA/platforms/odla_popart/popart_config.cc
ODLA/platforms/odla_popart/popart_config.h

* fix poplar sdk path symbol
* deserialize config in catch file
* Add error handling codes
Co-authored-by: yanwei <yw01041751@alibaba-inc.com>
Co-authored-by: gcuser <jackz@alibaba-inc.com>
Co-authored-by: gcuser <gcuser@alibaba-inc.com>
(cherry picked from commit 0b006c0ea3e2cf191fcbe879ef3899ef9b6e24dd)

Combine config cache (#659)

---

python/halo/odla.py

modified odla.py to support shoucai model

support for shoucai

---

ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_popart.cc
ODLA/platforms/odla_popart/odla_popart.h
ODLA/platforms/odla_popart/popart_config.cc
ODLA/platforms/odla_popart/popart_config.h

add inplementation of CreateExecutable and related updates

add inplementation of CreateExecutable

---

.github/actions/build/build_in_docker.sh
ODLA/platforms/odla_popart/odla_compute.cc
ODLA/platforms/odla_popart/odla_popart.cc
ODLA/platforms/odla_popart/odla_popart.h
ODLA/platforms/odla_popart/popart_config.cc
ODLA/platforms/odla_popart/popart_config.h

catch exception translate to ODLA_STATUS. and related updates

catch potential exception and handle

---

lib/transforms/inst_simplify.cc

Original code only handles for 1-D operand.

Fix bug in transpose simplification

---

lib/parser/tensorflow/tf_parser.cc

Original code assumes all nodes are in topological order.

[TFParser] Support unordered nodes

---

ODLA/include/ODLA/ops/odla_ops_math.h
include/halo/lib/ir/math_instructions.td
include/halo/lib/target/generic_cxx/generic_cxx_codegen.h
lib/target/generic_cpp/CMakeLists.txt
lib/target/generic_cpp/einsum.cc

Einsum op is used in Transformer-XL model.

[IR] Add support for Einsum IR.

---

lib/transforms/onnxextension_legalizer.cc

Fix the case when step is negative.

Fix ONNX Range

---

.github/actions/build/build_in_docker.sh
.github/workflows/main.yaml
utils/docker/Dockerfile
utils/docker/build_image.sh
utils/docker/start_docker_cpu.sh

Ops like Einsum are only supported in trt 8.2.0

[Docker] upgrade to cuda11.4.2 / trt 8.2.0

---

lib/transforms/analyzer.cc

* Add more info to the json file generated by analyzer.
* Modified by Lulu.

[Analyzer] Bugfix for json generation of analyzer.

---

.github/actions/build/build_in_docker.sh
utils/docker/Dockerfile
utils/docker/build_image.sh

[Docker] Update TRT to 8.2.1

---

include/halo/lib/ir/extension_instructions.h

Add support for DynCast / IsA for extension instructions.

[Util] Add support for casting to ExtensionInst

---

python/halo/halo.py
python/halo/inference.py
python/halo/odla.py

Complete Python api for AnalyzeModel.

---

.github/actions/build/build_in_docker.sh

This reverts commit 1546fde0a005fa9ab73cdfc4cd01078931e5a617.

Revert "[CI] Disable parallel tests"

---

include/halo/lib/ir/values.h
lib/parser/tensorflow/tf_parser.cc
lib/parser/tensorflow/tf_parser.h
lib/transforms/transforms_util.cc

Without control edges, nodes without data uses (no outgoing data edges)
will be treated as output nodes.

[TFParser] Add control deps

---

ODLA/include/ODLA/ops/odla_ops_process.h
ODLA/platforms/tensorrt/odla_tensorrt.cc
lib/target/generic_cpp/resize.cc

Add odla_ResizeDynamic to support dynamic resizing (input has dynamic
shape and/or scales/sizes are tensors)

Support resize with dynamic operands

---

ODLA/platforms/odla_popart/popart_config.cc

[ODLA/Popart] Bug fix std::move in config

---

include/halo/lib/ir/constant.h
lib/ir/constant.cc
lib/transforms/inst_simplify.cc

(cherry picked from commit d63a9055b6037d6bb05b51b9c4fc8f57d2d5c48a)

Fix the bug in recognition of zero tensors

---

include/halo/lib/transforms/analyzer.h
lib/interface/interface.cc
lib/transforms/analyzer.cc
python/halo/odla.py

Update cost model.
Now cost model suit for (qps, batchsize) input, and with GPU memory and GPU flops output.

Cmb vodla demo 0.2.1

---

.github/workflows/main.yaml
CMakeLists.txt
tests/driver/test_driver.cc

Modified CMakeLists to change HALO SDK name.

---

ODLA/include/ODLA/odla_device.h
ODLA/platforms/vodla/include/vodh_common.h
ODLA/platforms/vodla/vODLA.cpp

Update odla_AllocateDevice API and implementation for vodla.

[vODLA] update odla_AllocateDevice API

---

ODLA/platforms/dnnl/odla_dnnl.h

Fix the uncompilable issue in local environment.

---

ODLA/platforms/CMakeLists.txt
ODLA/platforms/tensorflow/CMakeLists.txt
ODLA/platforms/tensorflow/odla_tf.cc

Adds a Tensorflow inference wrapper for ODLA

ODLA: Add tf wrapper

---

ODLA/platforms/tensorrt/odla_tensorrt.cc

To correctly support input's dim > 2.

[ODLA] Bugfix for tensorrt odla_Gemm op.

---

ODLA/platforms/odla_popart/odla_pipeline.cc

Those lambdas are global and no need for capture list

ODLA/popart: fix build warning

---

ODLA/platforms/vodla/include/vodh_common.h
ODLA/platforms/vodla/makefile
ODLA/platforms/vodla/vODLA.cpp

Modified typedef vodla_context to keep consistence with vodh_sdk, and fixed several bug for odla_context.

vODLA Adapter

---

lib/transforms/onnxextension_legalizer.cc

In Opset 13, the numnber of inputs is 1-4:  X, [roi], [scales], and [sizes].
To determine the result size, we just need to check the last two
operands.

[ONNX] Fix for resize op

---

CMakeLists.txt
tests/driver/test_driver.cc

Version 0.7.6

---

ODLA/platforms/vodla/vODLA.cpp

Fixed a bug for data reuse in vODLA Adapter.

---

CMakeLists.txt
ODLA/platforms/vodla/vODLA.cpp
tests/driver/test_driver.cc

print tid in vODLA adapter

---

CMakeLists.txt
ODLA/platforms/vodla/vODLA.cpp
tests/driver/test_driver.cc

print thread id in vODLA Adapter

---

ODLA/platforms/vodla/include/vodh_common.h
ODLA/platforms/vodla/vODLA.cpp

[vODLA Adapter] Add model.cc modification detection.

---

ODLA/platforms/tensorrt/odla_tensorrt.cc

(cherry picked from commit 47cbb8c52b9bc01052521304140e2749e6b4b748)

[ODLA/TRT] fix:dilation for conv/deconv

---

lib/transforms/onnxextension_legalizer.cc

Signed-off-by: Peng Liang <pengliang.peng@alibaba-inc.com>
(cherry picked from commit 7c30897f8abb71a26bc6406227a3d0f8fc8e4018)

Onnx: fix convertsplit bug

---

lib/transforms/onnxextension_legalizer.cc

when step > 1, length should be (end - start - 1) / step + 1

[ONNX] fix length calcuation of slice

---

models/vision/invoke_halo.py
tests/compile/test_cxx_gen.in

Explicitly calling fini function to make sure cleanup is done properly

[tests] fix tests with random fail

---

.github/workflows/main.yaml
ODLA/platforms/CMakeLists.txt
ODLA/platforms/ascend/CMakeLists.txt
ODLA/platforms/ascend/inc/model_process.h
ODLA/platforms/ascend/inc/odla_ascend_acl.h
ODLA/platforms/ascend/src/model_process.cc
ODLA/platforms/ascend/src/odla_ascend_acl.cc
ODLA/platforms/ascend/src/odla_ops.cc

add ascend platform support for some odla operation

Ascend platform Support

---

ODLA/platforms/ascend/CMakeLists.txt
ODLA/platforms/ascend/src/odla_ascend_acl.cc
ODLA/platforms/ascend/src/odla_ops.cc

fix topk output error and  so link error

fix ascend platform code bug

---

ODLA/platforms/ascend/inc/odla_ascend_acl.h
ODLA/platforms/ascend/src/model_process.cc
ODLA/platforms/ascend/src/odla_ascend_acl.cc

add odla api impl for ascend platform

---

ODLA/platforms/tensorrt/odla_tensorrt.cc

Reuse buffer if data is smaller than current allocated buffer

[ODLA/TRT] optimize buffer use
