alibaba/heterogeneity-aware-lowering-and-optimization

ODLA/platforms/odla_tensorrt.cc
Currently, the TensorRT plugin has not been added to repo. So ODLA/TRT is not working due to missing symbols.
=> bugfix: temporarily disable TRT plugin loading

ODLA/include/ODLA/ops/odla_ops_process.h
The original interface can only add one dimension.
This new one is more generic.
=> [ODLA] Update odla_ExpandDims

ODLA/platforms/dnnl/dnnl_utils.h, ODLA/platforms/dnnl/dnnl_utils_avx512.h, ODLA/platforms/dnnl/odla_dnnl.cc
Wrap std::function and primitive into a unified "operation" struct
This allows API-like functions and dnnl::primitive to be executed in the same way
=> [ODLA DNNL] Wrap primitive into operation

ODLA/platforms/dnnl/dnnl_utils_avx512.h
_mm512_cmplt_ps_mask is not supported by GCC 10 for some reason.
Use _mm512_cmp_ps_mask instead.
=> [ODLA DNNL] Update intrinsics

lib/transforms/type_legalizer.cc
TF version of concat has an extra operand (the last operand) for axis. We need to remove it from inputs.
=> [Bug] Remove extra operand of concat

ODLA/platforms/dnnl/odla_dnnl.cc
halo doesn't check the gemm+add op's shape, so we need to see if the add op is bias_add  or not in odla_dnnl
=> [odla_dnnl] fix gemm bias fusion

tests/CMakeLists.txt
Target check-halo depends on target odla_tensorrt, odla_dnnl,odla_eigen etc, which in-turn are dependent on option ODLA_BUILD_TRT, ODLA_BUILD_DNNL,ODLA_BUILD_EIGEN respectively.
=> Fix a build error when building with some ODLA platform off

armory/analyzer/driver.cc, driver/driver.cc, include/halo/lib/transforms/input_legalizer.h, include/halo/utils/cl_options.h, lib/transforms/input_legalizer.cc
This pass is supposed to be run once.
When the input shape is overridden for batching size, the input shape is fixed.
Subsequent passes may further update the input shape for some optimizations. Rerun Input Shape Legalizer will cause side-effects.
This patch solves #198
=> Prevent re-entry of input type legalizer pass

ODLA/platforms/odla_profiler.cc
If ODLA_PROFILER_DUMP_PATH is set, profiler will dump all intermediate
values to the path.
=> [ODLA/Profiler] Support dump all values if env is set

cmake/modules/zbuild_llvm.cmake, driver/CMakeLists.txt, driver/driver.cc, include/halo/CMakeLists.txt, include/halo/version.h, tests/driver/test_driver.cc
Now, halo --version will output: HALO_VERSION, HALO REPO/REV and Build Type.
=> Support the print of vcs info in "--version" output

lib/transforms/type_legalizer.cc, tests/unittests/lit_cases/test_popart/test_averagepool_1d_default_popart.cc, tests/unittests/lit_cases/test_popart/test_convtranspose_1d_popart.cc, tests/unittests/lit_cases/test_popart/test_maxpool_1d_default_popart.cc
Currently, the conv & pooling only computes output shape for 4D tensors.
If input is 3D, out-of-bound access will occur.
=> [TypeLegalizer] Check dims of shape in for conv & pooling

include/halo/lib/framework/common.h, include/halo/lib/ir/instruction.h, lib/transforms/inst_simplify.cc, lib/transforms/onnxextension_legalizer.cc, utils/tablegen/inst.cc, utils/tablegen/inst.h
Originally, to check if an IRObject* is a specific instruction, it needs
to be written like:
`IsA<Instruction>(obj) && DynCast<Instruction>(obj)->GetOpCOde() == OpCode::XYZ`
This patch simplifies it to `IsA<XYZInstr>(obj)`
=> [Utils] Support DynCast/IsA with subclasses of Instruction

lib/transforms/inst_simplify.cc
The original code only handles slice with certain data types.
This patch extends to all data types.
=> [Opt] Handle constant input of all types for slice

armory/analyzer/driver.cc, driver/driver.cc, include/halo/lib/pass/pass_manager.h, include/halo/lib/target/generic_cxx/generic_cxx_codegen.h, include/halo/lib/transforms/analyzer.h, include/halo/utils/passes_helper.h, lib/pass/pass_manager.cc, lib/transforms/analyzer.cc, tests/compile/test_cxx_gen.in, tests/compile/test_llvm_ir_gen.cc, tests/compile/test_llvm_ir_gen_matmul.cc, tests/compile/test_llvm_ir_gen_pooling.cc, tests/compile/test_llvm_ir_gen_relu.cc, tests/compile/test_llvm_ir_gen_softmax.cc, tests/compile/x86/add.cc, tests/compile/x86/argmax.cc, tests/compile/x86/gather.cc, tests/compile/x86/reducemean.cc, tests/compile/x86/slice.cc, tests/compile/x86/transpose.cc, tests/ir/test_tf_batch_to_space.cc, tests/ir/test_tf_space_to_batch.cc, tests/transforms/test_fuse_scale_conv2d.cc
=> [Refactor] Decouple concrete passes from driver

utils/docker/runtime/Dockerfile.x86_64
Currently, halo will do code-fomat by itself, so we don't need to install external clang-tools
=> [Docker Runtime] Remove clang tools

lib/parser/onnx/onnx_parser.cc
The parameter "roi" in the resize module of yolov5 seems to be an empty tensor which has never been used. We ignored the check on roi because it is an unimportant error.
=> Ignore unimportant check.

ODLA/platforms/odla_popart/odla_compute.cc, ODLA/platforms/odla_popart/odla_popart.h
submit again. 
Run a model will cache the compiled executable file to the target path. This will be used to accelerate the start up process when open a new session to run the same model next time.
=> add detach device & move session to context and destory comp

lib/transforms/onnxextension_legalizer.cc, tests/unittests/lit_cases/test_dnnl/test_transpose_default_dnnl.cc, tests/unittests/lit_cases/test_popart/test_transpose_default_popart.cc, tests/unittests/lit_cases/test_tensorrt/test_transpose_default_tensorrt.cc, tests/unittests/lit_cases/test_xnnpack/test_transpose_default_xnnpack.cc
If perm is unspecified, ONNX assumes all axes are reversed.
=> [ONNX] Fix Transpose without `perm` attribute

.github/actions/build/build_in_docker.sh
Avoid building FileCheck during parallel jobs
Both "ninja check-halo" jobs will build FileCheck, which causes race condition.
=> [CI] Fix random build error

ODLA/platforms/dnnl/odla_dnnl.cc, ODLA/platforms/dnnl/odla_dnnl.h, ODLA/platforms/dnnl/odla_dnnl_statistics.cc, tests/unittests/lit_cases/test_dnnl/test_max_float16_dnnl.cc, tests/unittests/lit_cases/test_dnnl/test_min_float16_dnnl.cc
dnnl::memory only supports few data types. We need to track the actual
data type in odla_value.
=> [ODLA/DNNL] Refactor for memory type tracking

ODLA/platforms/odla_popart/odla_compute.cc, ODLA/platforms/odla_popart/odla_popart.cc, ODLA/platforms/odla_popart/odla_popart.h
Fixed the following parts:
1. Fixed the problem of default setting of ipu_num, batch_per_step etc set by popart_config.cc were used, which caused the parameters set did not take effect.
- Make the popart_config.cc set only take effect for pipeline to check whether the configuration consistent or not.
2. Fixed the problem of multiple device detach called, or device detach called during the pipeline is executing, which will cause the poplar exception or even exit.
- Add status checking for the computation destroy call, make the multiple call in sequence. And make it wait for the pipeline stage terminate(usually it takes less than 1s, it depends on the configuration of batches per step)
3. Fixed the problem computation destroy
- Make the singleton odla_computation from hungry to lazy
- Add …
=> fix on default configuration & computation destroyment

ODLA/include/ODLA/ops/odla_ops_nn.h, ODLA/platforms/dnnl/odla_dnnl.cc, include/halo/lib/ir/attribute_types.td, include/halo/lib/ir/nn_rnn_instructions.td, lib/target/generic_cpp/lstm.cc, lib/transforms/onnxextension_legalizer.cc
The data layout of LSTM is model-specific.
ONNX assumes LDGOI (layer, direction, gate, output chs, input chs).
And the gate ordering is also model-specific.
=> LSTM: Add attribute for data layout and gate order

include/halo/lib/ir/attribute_types.td, lib/parser/onnx/onnx_parser.cc
Special ops like ConstantOfShape uses tensor to represent the value to
fill, so we need correspoding value type.
=> Add int64 attribute type

lib/transforms/onnxextension_legalizer.cc
* When 'starts' or 'end' is non constant, currently the order of
'step' and 'axes' is wrongly handled.
* If 'step' is not set, then set 'step' to {1}.
=> [ONNX] Bugfix for Slice op leglization.

lib/transforms/inst_simplify.cc
When the length operand of slice is -1, it means taking all elements on
that dimension. Originally, inst simplification pass attemps to replace
-1 with actual dimension size.
However, -1 is also used to represent dynamic size, so it will make the
pass keep running.
=> [Fix] slice with dynamic batch

ODLA/include/ODLA/ops/odla_ops_process.h, include/halo/lib/ir/common_instructions.td, include/halo/lib/ir/tf_convert.td, include/halo/lib/target/generic_cxx/generic_cxx_codegen.h, include/halo/lib/transforms/inst_simplify.h, lib/target/generic_cpp/reshape.cc, lib/transforms/inst_simplify.cc, lib/transforms/tfextension_legalizer.cc, lib/transforms/type_legalizer.cc
With static shapes, all shape operations are converted to constants during
optimization pass.
But with dynamic shapes, we need shape IR to represent runtime shape
info.
=> IR: Add Shape Inst

ODLA/include/ODLA/ops/odla_ops_math.h, ODLA/platforms/dnnl/odla_dnnl_statistics.cc, ODLA/platforms/tensorrt/odla_tensorrt.cc, include/halo/lib/ir/common_reduction_instructions.td, include/halo/lib/target/generic_cxx/generic_cxx_codegen.h, lib/target/generic_cpp/reduction.cc
To avoid possible divid by zero, Caffe Norm has a epsilon value.
=> Add epsilon to LpNorm

driver/driver.cc, include/halo/lib/pass/pass_manager.h, include/halo/utils/passes_helper.h, lib/pass/pass_manager.cc
Using -target cxx-<target> to generate .bin file of other target.
For example: -target cxx-aarch64
(cherry picked from commit c86445c913b47045ee286cac57bcb0c7985e4641)
=> Support emitting .bin file of other target

python/halo/odla.py
This is a bug found in running mlperf bert-squad pipeline.
=> [Python Api] Use 'arg_v' as a pointer instead of integer when passing to 'odla_BindToArgument'.

ODLA/platforms/tensorflow/odla_tf.cc, ODLA/platforms/tensorrt/odla_tensorrt.cc
Since cuda current device is a TLS variable, if ODLA apis are called in different thread context, we need to set current device again.
=> [ODLA/TRT] Support multiple device instances and concurrent computation

.github/actions/build/build_in_docker.sh, .github/workflows/main.yaml, ODLA/platforms/odla_popart/CMakeLists.txt, ODLA/platforms/odla_popart/common.cc, ODLA/platforms/odla_popart/custom_ops/CMakeLists.txt, ODLA/platforms/odla_popart/custom_ops/rsqrt.cc, ODLA/platforms/odla_popart/odla_popart.cc, ODLA/platforms/odla_popart/odla_popart.h, ODLA/platforms/odla_popart/test/CMakeLists.txt, tests/unittests/lit_cases/test_popart/test_pow_types_int32_int32_popart.cc
This patch adds support for the newest poplar sdk on the following test setup.
Docker image:
registry-intl.us-west-1.aliyuncs.com/computation/halo:0.8.1-devel-cuda11.4.2-cudnn8-centos7
SDK:
poplar_sdk-centos_7_6-3.1.0-EA.1+1168-a2e17bf73e
Test command line:
cmake -G Ninja .. -DHALO_USE_TIDY_CHECK=OFF -DHALO_GEN_DOCS=OFF -DPOPLAR_ROOT=$POPLAR_ROOT \
-DPOPLAR_VERSION=$POPLAR_VERSION -DPOPART_ROOT=$POPART_ROOT -DODLA_BUILD_POPART_USE_CXX11ABI=ON \
-DODLA_BUILD_POPART_CUSTOM_OPS=ON -DHALO_BUILD_RTLIB=OFF -DODLA_BUILD_TRT=OFF \
-DODLA_BUILD_XNNPACK=OFF -DODLA_BUILD_EIGEN=OFF -DODLA_BUILD_DNNL=OFF \
-DCMAKE_BUILD_TYPE=Debug -DODLA_BUILD_VODLA=off
time ninja
Signed-off-by: Wei Xu <weix@graphcore.ai>
=> odla_popart: add support for graphcore poplar sdk 3.1.0
